### ISSUE TITLE
Feat - Incremental download begin date

### ISSUE THREAD

**Issue by Adrien-Pajot** [lpoaura/GN2PG#15]
Hi @lpofredc , 
I don't know what you planned to do but after discussing with JP Milcent from the CBNA, I think it is interesting to configure a begin date of the incremental download (in the config file ?). For large dataset, it will allow a first manual import and then start incremental downloads from a defined date thanks to your log history table. 

Was it your vision ? 

Thanks for your opinion !

**Comment by lpofredc** [comment]
Hi @Adrien-Pajot ,
That's exactly what incremental download do. 
* When you proceed to to first full download, download timestamp is logged in database.
* When you proceed to incremental download, timestamp of download start is logged in database. So, gn2pg first try to retrieve thist last incremental timestamp. If None (because not any incremental have already beed launched), then it get last full download timestamp.
Then this timestamp is used to limit returns from export API using awesome [PnX-SI/Utils-Flask-SQLAlchemy](
https://github.com/PnX-SI/Utils-Flask-SQLAlchemy/blob/be3cb4770e16c73f3d1e0d05a6143184e361fc46/src/utils_flask_sqla/generic.py#L212-L214) advanced filters `filter_d_up_<datetime_field_name>`.

https://github.com/lpoaura/GN2PG/blob/332705cc843568b776c06e1348ba6bc8bcb81bb3/gn2pg/download.py#L134-L147

**Comment by Adrien-Pajot** [comment]
Hi @lpofredc , 

Thanks for the answer. 
My question was in the context of an incremental download without a first full download. So, the solution is to go in the database and to manually enter a timestamp if I understand ?

**Comment by lpofredc** [comment]
Yes @Adrien-Pajot , that's it

**Comment by Adrien-Pajot** [comment]
Therefore, I think it would be good to enter a date in the config file that fills the timestamp in the database in the case of a manual import before incremental downloads.

The workflow would be : 
1. Manual import of all data before 2021 for example 
2. Entering 1/01/2021 00:00 in the config file for the begin date of the incremental downloads
3. Launching the incremental downloads each X days with the CRON

What do you think ?

**Comment by camillemonchicourt** [comment]
Incremental download has been included in the new release 0.1.0-dev, thanks.
Does it depends on this GeoNature PR (https://github.com/PnX-SI/GeoNature/pull/1456) to work ?

**Comment by lpofredc** [comment]
Yes, this merge is necessary on the GeoNature source instance to allow for incremental updating by providing searchable logs of updates made on data (Create, Update, Delete).

**Comment by lpofredc** [comment]
>     3. Launching the incremental downloads each X days with the CRON

Crontask is documented here https://gn2pg.readthedocs.io/en/latest/howto.html#incremental-download

**Comment by camillemonchicourt** [comment]
L'historisation des suppressions dans la Synthèse, nécessaire à une utilisation incrémentale de GN2PG a été finalisée et intégrée dans la version 2.12.0 de GeoNature.

**Comment by lpofredc** [comment]
This could now be configured in config file, in `[source.query_strings]` options

https://github.com/lpoaura/GN2PG/blob/main/gn2pg/data/gn2pgconfig.toml#L36-L37
